"use client";
import { useEffect,useState } from "react";import dynamic from "next/dynamic";import { milestones } from "@/data/milestones";import { useJourneyStore } from "@/stores/journeyStore";import QuickProfile from "@/components/portfolio/QuickProfile";import { clamp } from "@/lib/utils";
const Experience=dynamic(()=>import("@/components/world/Experience"),{ssr:false,loading:()=> <div className="scene-loading">LOADING 3D WORLD…</div>});
export default function JourneyApp(){const [quick,setQuick]=useState(false);const [reduced,setReduced]=useState(false);const {progress,currentMilestone,started,language,quality,soundEnabled,start,setProgress,setCurrentMilestone,setLanguage,toggleQuality,toggleSound}=useJourneyStore();
 useEffect(()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");setReduced(media.matches);const onChange=()=>setReduced(media.matches);media.addEventListener("change",onChange);return()=>media.removeEventListener("change",onChange)},[]);
 useEffect(()=>{const onScroll=()=>{if(!started)return;const max=document.documentElement.scrollHeight-innerHeight;const p=clamp(scrollY/Math.max(max,1));setProgress(p);const next=Math.min(milestones.length-1,Math.floor(p*milestones.length));setCurrentMilestone(p<.035?-1:next)};addEventListener("scroll",onScroll,{passive:true});onScroll();return()=>removeEventListener("scroll",onScroll)},[started,setProgress,setCurrentMilestone]);
 const active=currentMilestone>=0?milestones[currentMilestone]:null;
 const begin=()=>{start();requestAnimationFrame(()=>scrollTo({top:innerHeight*.86,behavior:reduced?"auto":"smooth"}))};
 if(quick||reduced)return <><QuickProfile onClose={()=>{setQuick(false);if(reduced)scrollTo(0,0)}}/><button className="floating-return" onClick={()=>setQuick(false)}>3D JOURNEY ↗</button></>;
 return <div className={`journey-shell ${started?"is-started":""}`}><Experience/><header className="topbar"><a className="logo" href="#garage"><b>M</b><span>MARCUS <i>JOURNEY</i></span></a><nav aria-label="Utility navigation"><button onClick={()=>setQuick(true)}>Quick Profile</button><a href="#projects">Projects</a><a href="/cv/marcus-tran-cv.pdf" download>Download CV</a></nav><div className="controls"><button onClick={toggleSound} aria-label="Toggle sound">SOUND {soundEnabled?"ON":"OFF"}</button><button onClick={toggleQuality}>QUALITY {quality.toUpperCase()}</button><select value={language} onChange={e=>setLanguage(e.target.value as "vi"|"en"|"zh")} aria-label="Language"><option value="vi">VI</option><option value="en">EN</option><option value="zh">中文</option></select></div></header>
 <section id="garage" className="garage"><div className="garage-lines"/><div className="hero-copy"><span className="kicker">PRODUCTION • KAIZEN • TECHNOLOGY</span><h1>MARCUS<br/><i>JOURNEY</i></h1><p>From Production Floor<br/>to Digital Innovation.</p><div className="hero-actions"><button className="main-cta" onClick={begin}>START THE JOURNEY <b>→</b></button><button onClick={()=>setQuick(true)}>QUICK PROFILE</button></div></div><div className="build-line">BUILD. <span>IMPROVE.</span> AUTOMATE.</div><div className="scroll-cue">SCROLL TO DRIVE <b>↓</b></div></section>
 {started&&<><aside className="progress-ui"><div className="progress-track"><span style={{height:`${progress*100}%`}}/></div><div><small>JOURNEY PROGRESS</small><strong>{String(Math.round(progress*100)).padStart(2,"0")}%</strong></div></aside><div className="mode-switch"><button className="active">AUTO JOURNEY</button><button disabled title="Coming soon">DRIVE MODE · SOON</button></div>{active&&<aside className="milestone-panel" style={{"--accent":active.accent} as React.CSSProperties}><span className="panel-index">{String(currentMilestone+1).padStart(2,"0")} / {String(milestones.length).padStart(2,"0")}</span><span className="kicker">{active.period}</span><h2>{active.title}</h2><h3>{active.role}</h3><p>{active.summary}</p><ul>{active.highlights.slice(0,3).map(h=><li key={h}>{h}</li>)}</ul><div className="upgrade">UPGRADE UNLOCKED <b>{active.upgrade}</b></div></aside>}</>}
 <div className="scroll-space" aria-hidden="true"/><section id="projects" className="final-cta"><span className="kicker">DESTINATION · SMART FACTORY</span><h2>Build systems that<br/><i>move people forward.</i></h2><p>I understand the factory floor. I improve the process.<br/>I build the system. I teach others to use it.</p><div><a href="/cv/marcus-tran-cv.pdf">DOWNLOAD CV ↗</a><button onClick={()=>setQuick(true)}>VIEW PROJECTS ↗</button><a href="mailto:hello@marcusjourney.dev">CONTACT ME ↗</a><a href="https://github.com" target="_blank" rel="noreferrer">GITHUB ↗</a></div></section></div>}
